// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  BlockComment = 2,
  Program = 3,
  String = 4,
  Number = 5,
  ControlKeyword = 6,
  OtherKeyword = 7,
  ModifierKeyword = 8,
  TypeKeyword = 9,
  TypeName = 10,
  Self = 11,
  Identifier = 12,
  Operator = 13,
  Block = 14,
  FunctionSignature = 15,
  FunctionParameter = 16
